# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# set working directory
WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir fastmcp robin_stocks pydantic

# copy source code
COPY . .

# default command
CMD ["python3", "server.py"]
